server:
  port: 8081

spring:
  application:
    name: hmdp

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dianping?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_DATABASE_PASSWORD}
  
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${REDIS_DATABASE_PASSWORD}
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: NON_NULL # JSON 处理时忽略 null

  rabbitmq:
    host: ${WSL_IP}
    port: 5672
    virtual-host: /
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    # 配置消费者监听器
    listener:
      simple:
        # 监听器容器的并发消费者数量初始值为 5
        concurrency: 5

        # 监听器容器的最大并发消费者数量为 10
        max-concurrency: 10

        # 每个消费者每次只能获取一条消息，处理完成才能获取下一个消息
        prefetch: 1

        # 项目启动时启动监听器容器
        auto-startup: true

        # 手动 ack
        acknowledge-mode: manual

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    '[com.hmdp]': debug
    '[org.springframework.jdbc.support.JdbcTransactionManager]': debug